/** Static SOP markup (matches legacy puzzle.html). */
export const SOP_INNER_HTML = `
<div class="sop-section"><div class="sop-section-num">01</div><div class="sop-section-content"><h4>Objective</h4><p>Build a quantum circuit implementing <strong>Booth's multiplication algorithm</strong> for two 2-bit numbers (0&ndash;3). The product must appear in P, inputs must be preserved.</p></div></div>
<div class="sop-section"><div class="sop-section-num">02</div><div class="sop-section-content"><h4>Interface Layout</h4><div class="sop-layout-grid"><div class="sop-area" style="border-color:var(--cyan)"><span class="sop-area-label">Left Panel</span><span class="sop-area-desc">Inputs &amp; gate palette</span></div><div class="sop-area" style="border-color:var(--green)"><span class="sop-area-label">Center</span><span class="sop-area-desc">Circuit grid</span></div><div class="sop-area" style="border-color:var(--purple)"><span class="sop-area-label">Right Panel</span><span class="sop-area-desc">Target, hints, controls, metrics</span></div></div></div></div>
<div class="sop-section"><div class="sop-section-num">03</div><div class="sop-section-content"><h4>Gate Reference</h4><div class="sop-gate-table"><div class="sop-gate-row"><span class="sop-gate-badge" style="background:rgba(0,229,255,0.15);color:var(--cyan)">X</span><div><strong>Pauli-X (NOT)</strong><span>Flips qubit. 1 click.</span></div></div><div class="sop-gate-row"><span class="sop-gate-badge" style="background:rgba(179,136,255,0.15);color:var(--purple)">CX</span><div><strong>CNOT</strong><span>Flips target IF control=|1&rang;. 2 clicks.</span></div></div><div class="sop-gate-row"><span class="sop-gate-badge" style="background:rgba(255,45,111,0.15);color:var(--pink)">CCX</span><div><strong>Toffoli</strong><span>Flips target IF both controls=|1&rang;. 3 clicks.</span></div></div></div></div></div>
<div class="sop-section"><div class="sop-section-num">04</div><div class="sop-section-content"><h4>Qubit Registers</h4><div class="sop-reg-table"><div class="sop-reg-row"><span class="sop-reg-dot" style="background:var(--cyan)"></span><strong>A</strong><span>Multiplicand</span></div><div class="sop-reg-row"><span class="sop-reg-dot" style="background:var(--purple)"></span><strong>B</strong><span>Multiplier</span></div><div class="sop-reg-row"><span class="sop-reg-dot" style="background:var(--green)"></span><strong>P</strong><span>Product</span></div><div class="sop-reg-row"><span class="sop-reg-dot" style="background:var(--yellow)"></span><strong>E</strong><span>Booth encoding</span></div><div class="sop-reg-row"><span class="sop-reg-dot" style="background:var(--orange)"></span><strong>C</strong><span>Carry</span></div></div></div></div>
<div class="sop-section"><div class="sop-section-num">05</div><div class="sop-section-content"><h4>Procedure</h4><div class="sop-steps"><div class="sop-step"><span class="sop-step-num">1</span><div><strong>Choose Inputs</strong><p>Select A and B from the left panel.</p></div></div><div class="sop-step"><span class="sop-step-num">2</span><div><strong>Initialize</strong><p>X gates in column 1.</p></div></div><div class="sop-step"><span class="sop-step-num">3</span><div><strong>Booth Encode</strong><p>Compute e0, e1 from B.</p></div></div><div class="sop-step"><span class="sop-step-num">4</span><div><strong>Process d0 = -b0</strong><p>Subtract A at position 0.</p></div></div><div class="sop-step"><span class="sop-step-num">5</span><div><strong>Process d1 = b0-b1</strong><p>Add/subtract A at position 1.</p></div></div><div class="sop-step"><span class="sop-step-num">6</span><div><strong>Process d2 = b1</strong><p>Add A at position 2.</p></div></div><div class="sop-step"><span class="sop-step-num">7</span><div><strong>Verify</strong><p>Check Circuit.</p></div></div></div></div></div>
<div class="sop-section"><div class="sop-section-num">06</div><div class="sop-section-content"><h4>Controls</h4><div class="sop-controls-table"><div class="sop-ctrl-row"><span class="sop-ctrl-key">Click gate button</span><span>Select tool</span></div><div class="sop-ctrl-row"><span class="sop-ctrl-key">Click grid cell</span><span>Place gate</span></div><div class="sop-ctrl-row"><span class="sop-ctrl-key">Drag gate</span><span>Drop to place</span></div><div class="sop-ctrl-row"><span class="sop-ctrl-key">Click existing gate</span><span>Delete it</span></div></div></div></div>
<div class="sop-section"><div class="sop-section-num">07</div><div class="sop-section-content"><h4>Pro Tips</h4><div class="sop-tips"><div class="sop-tip">All clicks for multi-qubit gates must be in the <strong>same column</strong>.</div><div class="sop-tip">Booth subtraction = negate A + add + 1 (two's complement).</div><div class="sop-tip">Always uncompute carries after each phase.</div></div></div></div>
`.trim();
